//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBancario.Autenticar {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Autenticar.SecurityAutSoap")]
    public interface SecurityAutSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAcumulador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void setAcumulador(string acumulador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setAcumulador", ReplyAction="*")]
        System.Threading.Tasks.Task setAcumuladorAsync(string acumulador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAcumulador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getAcumulador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAcumulador", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAcumuladorAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje AutenticarRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaBancario.Autenticar.AutenticarResponse Autenticar(SistemaBancario.Autenticar.AutenticarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Autenticar", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.AutenticarResponse> AutenticarAsync(SistemaBancario.Autenticar.AutenticarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje DepocitarRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depocitar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaBancario.Autenticar.DepocitarResponse Depocitar(SistemaBancario.Autenticar.DepocitarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depocitar", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.DepocitarResponse> DepocitarAsync(SistemaBancario.Autenticar.DepocitarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje RetirarRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Retirar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaBancario.Autenticar.RetirarResponse Retirar(SistemaBancario.Autenticar.RetirarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Retirar", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.RetirarResponse> RetirarAsync(SistemaBancario.Autenticar.RetirarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje RegistrarRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaBancario.Autenticar.RegistrarResponse Registrar(SistemaBancario.Autenticar.RegistrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.RegistrarResponse> RegistrarAsync(SistemaBancario.Autenticar.RegistrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaBancario.Autenticar.AuthUser[] verSaldo(string b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.AuthUser[]> verSaldoAsync(string b);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_UsuarioField;
        
        private string nombreUsuarioField;
        
        private string nombreCuentaField;
        
        private string contraseñaField;
        
        private string numTelefonoField;
        
        private string saldoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id_Usuario {
            get {
                return this.id_UsuarioField;
            }
            set {
                this.id_UsuarioField = value;
                this.RaisePropertyChanged("id_Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("NombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreCuenta {
            get {
                return this.nombreCuentaField;
            }
            set {
                this.nombreCuentaField = value;
                this.RaisePropertyChanged("NombreCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("Contraseña");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NumTelefono {
            get {
                return this.numTelefonoField;
            }
            set {
                this.numTelefonoField = value;
                this.RaisePropertyChanged("NumTelefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Autenticar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SistemaBancario.Autenticar.AuthUser AuthUser;
        
        public AutenticarRequest() {
        }
        
        public AutenticarRequest(SistemaBancario.Autenticar.AuthUser AuthUser) {
            this.AuthUser = AuthUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AutenticarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AutenticarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AutenticarResult;
        
        public AutenticarResponse() {
        }
        
        public AutenticarResponse(string AutenticarResult) {
            this.AutenticarResult = AutenticarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Depocitar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DepocitarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SistemaBancario.Autenticar.AuthUser AuthUser;
        
        public DepocitarRequest() {
        }
        
        public DepocitarRequest(SistemaBancario.Autenticar.AuthUser AuthUser) {
            this.AuthUser = AuthUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepocitarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DepocitarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DepocitarResult;
        
        public DepocitarResponse() {
        }
        
        public DepocitarResponse(string DepocitarResult) {
            this.DepocitarResult = DepocitarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Retirar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RetirarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SistemaBancario.Autenticar.AuthUser AuthUser;
        
        public RetirarRequest() {
        }
        
        public RetirarRequest(SistemaBancario.Autenticar.AuthUser AuthUser) {
            this.AuthUser = AuthUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetirarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RetirarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RetirarResult;
        
        public RetirarResponse() {
        }
        
        public RetirarResponse(string RetirarResult) {
            this.RetirarResult = RetirarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Registrar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SistemaBancario.Autenticar.AuthUser AuthUser;
        
        public RegistrarRequest() {
        }
        
        public RegistrarRequest(SistemaBancario.Autenticar.AuthUser AuthUser) {
            this.AuthUser = AuthUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegistrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RegistrarResult;
        
        public RegistrarResponse() {
        }
        
        public RegistrarResponse(string RegistrarResult) {
            this.RegistrarResult = RegistrarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SecurityAutSoapChannel : SistemaBancario.Autenticar.SecurityAutSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityAutSoapClient : System.ServiceModel.ClientBase<SistemaBancario.Autenticar.SecurityAutSoap>, SistemaBancario.Autenticar.SecurityAutSoap {
        
        public SecurityAutSoapClient() {
        }
        
        public SecurityAutSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityAutSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityAutSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityAutSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void setAcumulador(string acumulador) {
            base.Channel.setAcumulador(acumulador);
        }
        
        public System.Threading.Tasks.Task setAcumuladorAsync(string acumulador) {
            return base.Channel.setAcumuladorAsync(acumulador);
        }
        
        public string getAcumulador() {
            return base.Channel.getAcumulador();
        }
        
        public System.Threading.Tasks.Task<string> getAcumuladorAsync() {
            return base.Channel.getAcumuladorAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.Autenticar.AutenticarResponse SistemaBancario.Autenticar.SecurityAutSoap.Autenticar(SistemaBancario.Autenticar.AutenticarRequest request) {
            return base.Channel.Autenticar(request);
        }
        
        public string Autenticar(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.AutenticarRequest inValue = new SistemaBancario.Autenticar.AutenticarRequest();
            inValue.AuthUser = AuthUser;
            SistemaBancario.Autenticar.AutenticarResponse retVal = ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).Autenticar(inValue);
            return retVal.AutenticarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.AutenticarResponse> SistemaBancario.Autenticar.SecurityAutSoap.AutenticarAsync(SistemaBancario.Autenticar.AutenticarRequest request) {
            return base.Channel.AutenticarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.Autenticar.AutenticarResponse> AutenticarAsync(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.AutenticarRequest inValue = new SistemaBancario.Autenticar.AutenticarRequest();
            inValue.AuthUser = AuthUser;
            return ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).AutenticarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.Autenticar.DepocitarResponse SistemaBancario.Autenticar.SecurityAutSoap.Depocitar(SistemaBancario.Autenticar.DepocitarRequest request) {
            return base.Channel.Depocitar(request);
        }
        
        public string Depocitar(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.DepocitarRequest inValue = new SistemaBancario.Autenticar.DepocitarRequest();
            inValue.AuthUser = AuthUser;
            SistemaBancario.Autenticar.DepocitarResponse retVal = ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).Depocitar(inValue);
            return retVal.DepocitarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.DepocitarResponse> SistemaBancario.Autenticar.SecurityAutSoap.DepocitarAsync(SistemaBancario.Autenticar.DepocitarRequest request) {
            return base.Channel.DepocitarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.Autenticar.DepocitarResponse> DepocitarAsync(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.DepocitarRequest inValue = new SistemaBancario.Autenticar.DepocitarRequest();
            inValue.AuthUser = AuthUser;
            return ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).DepocitarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.Autenticar.RetirarResponse SistemaBancario.Autenticar.SecurityAutSoap.Retirar(SistemaBancario.Autenticar.RetirarRequest request) {
            return base.Channel.Retirar(request);
        }
        
        public string Retirar(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.RetirarRequest inValue = new SistemaBancario.Autenticar.RetirarRequest();
            inValue.AuthUser = AuthUser;
            SistemaBancario.Autenticar.RetirarResponse retVal = ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).Retirar(inValue);
            return retVal.RetirarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.RetirarResponse> SistemaBancario.Autenticar.SecurityAutSoap.RetirarAsync(SistemaBancario.Autenticar.RetirarRequest request) {
            return base.Channel.RetirarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.Autenticar.RetirarResponse> RetirarAsync(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.RetirarRequest inValue = new SistemaBancario.Autenticar.RetirarRequest();
            inValue.AuthUser = AuthUser;
            return ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).RetirarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.Autenticar.RegistrarResponse SistemaBancario.Autenticar.SecurityAutSoap.Registrar(SistemaBancario.Autenticar.RegistrarRequest request) {
            return base.Channel.Registrar(request);
        }
        
        public string Registrar(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.RegistrarRequest inValue = new SistemaBancario.Autenticar.RegistrarRequest();
            inValue.AuthUser = AuthUser;
            SistemaBancario.Autenticar.RegistrarResponse retVal = ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).Registrar(inValue);
            return retVal.RegistrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.Autenticar.RegistrarResponse> SistemaBancario.Autenticar.SecurityAutSoap.RegistrarAsync(SistemaBancario.Autenticar.RegistrarRequest request) {
            return base.Channel.RegistrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.Autenticar.RegistrarResponse> RegistrarAsync(SistemaBancario.Autenticar.AuthUser AuthUser) {
            SistemaBancario.Autenticar.RegistrarRequest inValue = new SistemaBancario.Autenticar.RegistrarRequest();
            inValue.AuthUser = AuthUser;
            return ((SistemaBancario.Autenticar.SecurityAutSoap)(this)).RegistrarAsync(inValue);
        }
        
        public SistemaBancario.Autenticar.AuthUser[] verSaldo(string b) {
            return base.Channel.verSaldo(b);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.Autenticar.AuthUser[]> verSaldoAsync(string b) {
            return base.Channel.verSaldoAsync(b);
        }
    }
}
