//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBancario.ServicioBancario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioBancario.BancoServiceSoap")]
    public interface BancoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/codigoBanco", ReplyAction="*")]
        bool codigoBanco(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/codigoBanco", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> codigoBancoAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/codigoSucursal", ReplyAction="*")]
        bool codigoSucursal(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/codigoSucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> codigoSucursalAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroCuenta", ReplyAction="*")]
        bool numeroCuenta(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/numeroCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> numeroCuentaAsync(int x);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento x del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/contraseña", ReplyAction="*")]
        SistemaBancario.ServicioBancario.contraseñaResponse contraseña(SistemaBancario.ServicioBancario.contraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/contraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.contraseñaResponse> contraseñaAsync(SistemaBancario.ServicioBancario.contraseñaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento x del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/orden", ReplyAction="*")]
        SistemaBancario.ServicioBancario.ordenResponse orden(SistemaBancario.ServicioBancario.ordenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/orden", ReplyAction="*")]
        System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.ordenResponse> ordenAsync(SistemaBancario.ServicioBancario.ordenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contraseña", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBancario.ServicioBancario.contraseñaRequestBody Body;
        
        public contraseñaRequest() {
        }
        
        public contraseñaRequest(SistemaBancario.ServicioBancario.contraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class contraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        public contraseñaRequestBody() {
        }
        
        public contraseñaRequestBody(string x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="contraseñaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBancario.ServicioBancario.contraseñaResponseBody Body;
        
        public contraseñaResponse() {
        }
        
        public contraseñaResponse(SistemaBancario.ServicioBancario.contraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class contraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool contraseñaResult;
        
        public contraseñaResponseBody() {
        }
        
        public contraseñaResponseBody(bool contraseñaResult) {
            this.contraseñaResult = contraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="orden", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBancario.ServicioBancario.ordenRequestBody Body;
        
        public ordenRequest() {
        }
        
        public ordenRequest(SistemaBancario.ServicioBancario.ordenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ordenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        public ordenRequestBody() {
        }
        
        public ordenRequestBody(string x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ordenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ordenResponse", Namespace="http://tempuri.org/", Order=0)]
        public SistemaBancario.ServicioBancario.ordenResponseBody Body;
        
        public ordenResponse() {
        }
        
        public ordenResponse(SistemaBancario.ServicioBancario.ordenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ordenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ordenResult;
        
        public ordenResponseBody() {
        }
        
        public ordenResponseBody(string ordenResult) {
            this.ordenResult = ordenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoServiceSoapChannel : SistemaBancario.ServicioBancario.BancoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoServiceSoapClient : System.ServiceModel.ClientBase<SistemaBancario.ServicioBancario.BancoServiceSoap>, SistemaBancario.ServicioBancario.BancoServiceSoap {
        
        public BancoServiceSoapClient() {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool codigoBanco(int x) {
            return base.Channel.codigoBanco(x);
        }
        
        public System.Threading.Tasks.Task<bool> codigoBancoAsync(int x) {
            return base.Channel.codigoBancoAsync(x);
        }
        
        public bool codigoSucursal(int x) {
            return base.Channel.codigoSucursal(x);
        }
        
        public System.Threading.Tasks.Task<bool> codigoSucursalAsync(int x) {
            return base.Channel.codigoSucursalAsync(x);
        }
        
        public bool numeroCuenta(int x) {
            return base.Channel.numeroCuenta(x);
        }
        
        public System.Threading.Tasks.Task<bool> numeroCuentaAsync(int x) {
            return base.Channel.numeroCuentaAsync(x);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.ServicioBancario.contraseñaResponse SistemaBancario.ServicioBancario.BancoServiceSoap.contraseña(SistemaBancario.ServicioBancario.contraseñaRequest request) {
            return base.Channel.contraseña(request);
        }
        
        public bool contraseña(string x) {
            SistemaBancario.ServicioBancario.contraseñaRequest inValue = new SistemaBancario.ServicioBancario.contraseñaRequest();
            inValue.Body = new SistemaBancario.ServicioBancario.contraseñaRequestBody();
            inValue.Body.x = x;
            SistemaBancario.ServicioBancario.contraseñaResponse retVal = ((SistemaBancario.ServicioBancario.BancoServiceSoap)(this)).contraseña(inValue);
            return retVal.Body.contraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.contraseñaResponse> SistemaBancario.ServicioBancario.BancoServiceSoap.contraseñaAsync(SistemaBancario.ServicioBancario.contraseñaRequest request) {
            return base.Channel.contraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.contraseñaResponse> contraseñaAsync(string x) {
            SistemaBancario.ServicioBancario.contraseñaRequest inValue = new SistemaBancario.ServicioBancario.contraseñaRequest();
            inValue.Body = new SistemaBancario.ServicioBancario.contraseñaRequestBody();
            inValue.Body.x = x;
            return ((SistemaBancario.ServicioBancario.BancoServiceSoap)(this)).contraseñaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaBancario.ServicioBancario.ordenResponse SistemaBancario.ServicioBancario.BancoServiceSoap.orden(SistemaBancario.ServicioBancario.ordenRequest request) {
            return base.Channel.orden(request);
        }
        
        public string orden(string x) {
            SistemaBancario.ServicioBancario.ordenRequest inValue = new SistemaBancario.ServicioBancario.ordenRequest();
            inValue.Body = new SistemaBancario.ServicioBancario.ordenRequestBody();
            inValue.Body.x = x;
            SistemaBancario.ServicioBancario.ordenResponse retVal = ((SistemaBancario.ServicioBancario.BancoServiceSoap)(this)).orden(inValue);
            return retVal.Body.ordenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.ordenResponse> SistemaBancario.ServicioBancario.BancoServiceSoap.ordenAsync(SistemaBancario.ServicioBancario.ordenRequest request) {
            return base.Channel.ordenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SistemaBancario.ServicioBancario.ordenResponse> ordenAsync(string x) {
            SistemaBancario.ServicioBancario.ordenRequest inValue = new SistemaBancario.ServicioBancario.ordenRequest();
            inValue.Body = new SistemaBancario.ServicioBancario.ordenRequestBody();
            inValue.Body.x = x;
            return ((SistemaBancario.ServicioBancario.BancoServiceSoap)(this)).ordenAsync(inValue);
        }
    }
}
